### ISSUE TITLE
What is the minimum requirement for nodejs?

### ISSUE THREAD

**Issue by zh2120** [louis-tru/ngui#2]
我ngui 初始化，一运行，mac构建成功，但是无法打开演示应用
```
Inspector support is not available with this Node.js build
node: bad option: --inspect=0.0.0.0:9229
```

**Comment by louis-tru** [comment]
请问是在ios，还是android。ios release 版本是不支持 v8  inspect 调试器的，如果要使用inspect ，可切换到debug


On 3 Jan 2018, at 7:33 PM, traveller <notifications@github.com<mailto:notifications@github.com>> wrote:


我ngui 初始化，一运行，mac构建成功，但是无法打开演示应用

Inspector support is not available with this Node.js build
node: bad option: --inspect=0.0.0.0:9229

**Comment by louis-tru** [comment]
还有如果使用网络启动，需要在项目根目录运行，ngui命令启动 http调式服务器

比如这种方式启动 `--inspect=0.0.0.0:9229 http://192.168.1.10:1026/examples --dev --ignore-local=* `

On 3 Jan 2018, at 7:33 PM, traveller <notifications@github.com<mailto:notifications@github.com>> wrote:


我ngui 初始化，一运行，mac构建成功，但是无法打开演示应用

Inspector support is not available with this Node.js build
node: bad option: --inspect=0.0.0.0:9229

**Comment by zh2120** [comment]
ios上进行的。
按照开始步骤一步步来的，ngui export 导出myproject后，用xcode 打开后，ngui命令启动 http调式服务器也打开了构建成功，但是无法打开应用，一打开就闪退。应该是我哪里没对，xcode控制台，显示
```
Inspector support is not available with this Node.js build
node: bad option: --inspect=0.0.0.0:9229
```

**Comment by louis-tru** [comment]
我在本地用npm安装试试，因为之前都是我直接编译安装的

**Comment by louis-tru** [comment]
请问你是用的模拟器还是真机，我刚刚试了模拟器确定有问题，但真机没有问题。
我一会修改一下编译参数Build一个新版本。

**Comment by zh2120** [comment]
是模拟ios的模拟器，iPhone6

**Comment by louis-tru** [comment]
v0.2.2版本已上传到npm，模拟器的问题已修复。

**Comment by zh2120** [comment]
大佬，崇拜！
