### ISSUE TITLE
Langou不就是和Flutter差不多

### ISSUE THREAD

**Issue by udbmnm** [louis-tru/ngui#8]
如题，Langou不就是和Flutter差不多？很超前，并且还是支持node和jsx的

**Comment by louis-tru** [comment]
现在很难遇到像你这样有见识的人了

**Comment by udbmnm** [comment]
JSX和CSS比Flutter的嵌套语法还方便点

**Comment by liyujiang-gzu** [comment]
的确，感觉就是和flutter一样的思路，都是高性能堪比native开发啊。

flutter是skia绘制，dartvm执行；ngui则是opengl绘制，node执行。

**Comment by liyujiang-gzu** [comment]
> JSX和CSS比Flutter的嵌套语法还方便点

flutter嵌套语法其实可以使用封装复用的思想啊，万物皆部件，多封装widget或者抽取函数，就不会出现嵌套深了。

**Comment by udbmnm** [comment]
> > JSX和CSS比Flutter的嵌套语法还方便点
> 
> flutter嵌套语法其实可以使用封装复用的思想啊，万物皆部件，多封装widget或者抽取函数，就不会出现嵌套深了。**一切都是小部件**这个理念感觉特别好！

写react就是这个感觉
